version: 0.2

env:
  variables:
    ECR_REPO: 375262246137.dkr.ecr.us-east-1.amazonaws.com/course-catalog
    ECR_REGION: us-east-1
    CONTAINER_NAME: course-catalog

    phases:
      install:
        runtime-versions:
          nodejs: 16
          docker: 20
      pre_build:
        commands:
          - echo "Install Denpendencies and login into ECR"
      post_build:
        commands:
          - echo "push the image to ECR.."
          - print '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${ECR_REPO}:latest > imagedefinitions.json
          - echo "build complete.."
      reports:
        test-repost:
          files:
            - 'report/test-result.xml'
          file-format: JUNITXML
      artifacts:
        files:
          - imagedefinitions.json
